name: Revive
version: '1.0'
api-version: '1.13'
author: Donut
main: us.donut.revive.Main
depend: [HolographicDisplays]
command:
  reloadrevive:
    permission:
      revive.reload
permissions:
  revive.disable:
    description: Prevents a player from being disabled
    default: false
  revive.reload:
    description: Allows /reloadrevive